# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENrL1cpgv1-qtqwzykFBwoukCwwWeFez
"""

import pandas as pd
import numpy as np
import torch as th
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

df = pd.read_csv("crop.csv")
print(df.head())

X = df.drop("Crop", axis = 1).values
y = df['Crop'].values

encoder = LabelEncoder()
y = encoder.fit_transform(y)

scaler = StandardScaler()
X = scaler.fit_transform(X)

train_x, test_x, train_y, test_y = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

if th.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

lr = 0.001
nb_epochs = 200
batch_size = 32

nb_train = len(train_y)
nb_batches = int(nb_train / batch_size)

nb_input = train_x.shape[1]
nb_hidden1 = 64
nb_hidden2 = 32
nb_classes = len(np.unique(y))

w = {
    '1': th.randn(
        [nb_input, nb_hidden1],
        dtype = th.float64,
        requires_grad = True,
        device = device
    ),

    '2': th.randn(
      [nb_hidden1, nb_hidden2],
      dtype = th.float64,
      requires_grad = True,
      device = device
    ),

    'out': th.randn(
        [nb_hidden2, nb_classes],
        dtype = th.float64,
        requires_grad = True,
        device = device
    )
}

b = {
    '1': th.zeros(
        [nb_hidden1],
        dtype = th.float64,
        requires_grad = True,
        device = device
    ),
    '2': th.zeros(
        [nb_hidden2],
        dtype = th.float64,
        requires_grad = True,
        device = device
    ),

    'out': th.zeros(
        [nb_classes],
        dtype = th.float64,
        requires_grad = True,
        device = device
    )
}

th.nn.init.kaiming_uniform_(
    w['1'],
    a = th.sqrt(th.tensor(5.0)),
    mode = 'fan_in',
    nonlinearity = 'relu'
)

th.nn.init.kaiming_uniform_(
    w['2'],
    a = th.sqrt(th.tensor(5.0)),
    mode = 'fan_in',
    nonlinearity = 'relu'
)

th.nn.init.kaiming_uniform_(
    w['out'],
    a = th.sqrt(th.tensor(5.0)),
    mode = 'fan_in',
    nonlinearity = 'relu'
)

relu = th.nn.ReLU()

def forward(x):
  z1 = x @ w['1'] + b['1']
  a1 = relu(z1)

  z2 = a1 @ w['2'] + b['2']
  a2 = relu(z2)

  z_out = a2 @ w['out'] + b['out']

  out = th.softmax(z_out, dim = 1)

  pred = th.argmax(out, dim = 1)

  return pred, out

for epoch in range(nb_epochs):
  epoch_loss = 0
  for batch in range(nb_batches):
    start = batch * batch_size
    end = (batch + 1) * batch_size

    x = th.tensor(
        train_x[start:end],
        dtype = th.float64,
        device = device
    )

    y_batch = th.tensor(
        train_y[start:end],
        device = device
    )

    y_onehot = th.nn.functional.one_hot(
        y_batch,
        nb_classes
    ).double()

    pred, out = forward(x)

    loss = -(y_onehot * th.log(out + 1e-8)).sum()

    loss.backward()

    with th.no_grad():
      w['1'] -= lr * w['1'].grad
      w['2'] -= lr * w['2'].grad
      w['out'] -= lr * w['out'].grad

      b['1'] -= lr * b['1'].grad
      b['2'] -= lr * b['2'].grad
      b['out'] -= lr * b['out'].grad

    w['1'].grad.zero_()
    w['2'].grad.zero_()
    w['out'].grad.zero_()

    b['1'].grad.zero_()
    b['2'].grad.zero_()
    b['out'].grad.zero_()

    epoch_loss += loss.item()

  epoch_loss /= nb_batches
  print(f'Epoch {epoch+1}/{nb_epochs} | Loss: {epoch_loss:.4f}')

x_test = th.tensor(
    test_x,
    dtype = th.float64,
    device = device
)

y_test = th.tensor(
    test_y,
    device = device
)

pred, _ = forward(x_test)

accuracy = th.mean(
    (pred == y_test).float()
)

print(f'\nTacnost: {accuracy*100:.2f}%')